<?php
?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Adas - Daily summary</title>
    <!-- CSS -->
    <link href='//fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
    <link href="//tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href='//tools.wmflabs.org/raun/css/style.css' rel='stylesheet' type='text/css'> <!-- super lazy custom style declaration :P -->
    <style>
.list-group-item-text.item-rev {
    display:flex;
    flex-direction: row;
    flex-wrap: wrap;
}
.list-group-item-text .item-time,
.list-group-item-text .item-user,
.list-group-item-text .item-score,
.list-group-item-text .item-type,
.list-group-item-text .item-action {
    flex: 0 1 200px;

}

    </style>
</head>
<body>
    <header class="container">
        <div class="page-header">
            <h1>Adas - Daily summary</h1>
        </div>
    </header>
    <main class="container">
        <?php
        foreach ($this->data as $row) {
            ?>
            <div class="card list-group-item ns ns-<?=$row['ns']?>">
                <h4 class="list-group-item-heading link">
                    <a href="https://id.wikipedia.org/wiki/<?=$row['title']?>"><?= $row['title'];?></a>
                </h4>
                <?php 
                foreach ($row['revisions'] as $revision) {
                    ?>
                <div class="list-group-item-text item-rev">
                    <div class="item-time"><span class="glyphicon glyphicon-time"></span> <?php
                        if ($revision['diff'] > 0) {

                        ?><a href="https://id.wikipedia.org/wiki/Special:Diff/<?= $revision['diff'] ?>"><?php

                        }
                            echo date("H:i:s", $revision['timestamp']);
                        if ($revision['diff'] > 0) {
                            echo "</a>";
                        }
                            ?></div>
                    <div class="item-user"><span class="glyphicon glyphicon-user"></span> <a href="https://id.wikipedia.org/wiki/Special:Contributions/<?= $revision['user'] ?>"><?= $revision['user'] ?></a></div>
                    <div class="item-score"><?php if (strlen($revision['diff_score']) > 0) { ?><span class="glyphicon glyphicon-fire"></span> <?= $revision['diff_score'] ?>% <?php } ?>(<?= $revision['type'] ?>)</div>
                    <div class="item-type"><?= $revision['log_type'] ?></div>
                    <div class="item-action"><?= $revision['log_action'] ?></div>
                </div>
                    <?php
                }
                ?>
            </div>
            <?php
        };
        ?>
    </main>
    <footer>
        <div class="container"> 
            &copy; <?php echo date("Y"); ?> Adas
        </div>
    </footer>
    <script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
    <script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>