<?php
?><!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Adas - Home</title>
    <!-- CSS -->
    <link href='//fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
    <link href="//tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="//tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap-datepicker/1.5.1/css/bootstrap-datepicker3.min.css" rel="stylesheet">
</head>
<body>
    <header class="container">
        <div class="page-header">
            <h1>Adas</h1>
        </div>
    </header>
    <main class="container">
        <div class=" col-sm-4 col-sm-offset-4">
            <form id="form" action="daily_summary" class="form-horizontal">
                <div class="form-group">
                    <label for="date" class="col-sm-2 control-label">Date</label>
                    <div class="col-sm-10">
                        <input data-provide="datepicker" id="date" class="form-control" required="required">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="submit" type="submit" class="btn btn-primary">Get summary</button>
                    </div>
                </div>
            </form>
        </div>

    </main>
    <footer>
        <div class="container"> 
            &copy; <?php echo date("Y"); ?> Adas
        </div>
    </footer>
    <script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
    <script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="//tools-static.wmflabs.org/cdnjs/ajax/libs/bootstrap-datepicker/1.5.1/js/bootstrap-datepicker.min.js"></script>
    <script>
    $(document).ready(function () {
        var curDate = new Date();
        $('#date').datepicker({
            format: "yyyy-mm-dd",
            startDate: "-90d",
            endDate: "-1d",
            defaultViewDate: { year: curDate.getUTCFullYear(), month: curDate.getUTCMonth(), day: curDate.getUTCDate() }
        });
        $("#submit").click(function () {
            $('#form').attr('action', 'daily_summary/' + $('#date').val());
            $('#form').submit();
        });
        $("#form").submit(function (e) {
            if ($("#form").attr("action").indexOf("/") < 0) {
                $('#form').attr('action', 'daily_summary/' + $('#date').val());
            }
            
        });
    });
    
    </script>
</body>
</html>